TYPES = ["product", "book"]

CATEGORIES = [
    "Accessories",
    "Appliances",
    "Arts & Photography",
    "Arts, Crafts & Sewing",
    "Automotive",
    "Baby Care",
    "Baby Products",
    "Bath",
    "Beauty & Personal Care",
    "Bedding",
    "Beverages",
    "Biographies & Memoirs",
    "Books",
    "CDs & Vinyl",
    "Camera & Photo",
    "Cell Phones & Accessories",
    "Children's Books",
    "Christian Books & Bibles",
    "Classical",
    "Clothing, Shoes & Jewelry",
    "Computers & Accessories",
    "Costumes & Accessories",
    "Dogs",
    "Electrical",
    "Electronics",
    "Event & Party Supplies",
    "Exercise & Fitness",
    "Exterior Accessories",
    "GPS, Finders & Accessories",
    "Grocery & Gourmet Food",
    "Hair Care",
    "Health & Household",
    "Home & Kitchen",
    "Hunting & Fishing",
    "Industrial & Scientific",
    "Industrial Electrical",
    "Kitchen & Dining",
    "Lighting Assemblies & Accessories",
    "Lights & Lighting Accessories",
    "Luggage & Travel Gear",
    "Makeup",
    "Medical Supplies & Equipment",
    "Men",
    "Movies & TV",
    "Musical Instruments",
    "Office & School Supplies",
    "Office Products",
    "Patio Furniture & Accessories",
    "Patio, Lawn & Garden",
    "Pet Supplies",
    "Pop",
    "Portable Audio & Video",
    "Power & Hand Tools",
    "Raw Materials",
    "Replacement Parts",
    "Self-Help",
    "Sports & Outdoor Play",
    "Sports & Outdoors",
    "Stuffed Animals & Plush Toys",
    "Tires & Wheels",
    "Tools & Home Improvement",
    "Toy Figures & Playsets",
    "Toys & Games",
    "Vehicles",
    "Video Games",
    "Wall Art",
    "Women",
]